### ISSUE TITLE
[Feature] How to add support for new models?

### ISSUE THREAD

**Issue by xpirad** [aka-katto/dandere2x#111]
i.e. waifu2x is a bit outdated and didn't perform well enough in some cases.
There has been new and better performance models out there like ESRGAN, EDVR, PPON.
How to add support for these new models?
Like, will there be a standard api so that new model support can be added easily?

And, thanks for making this amazing tool!!!

**Comment by aka-katto** [comment]
https://www.reddit.com/r/Dandere2x/comments/blib5e/dandere2x_sort_of_works_with_gans_gigapixel_ai/

Dandere2x is compatible with GAN's, although it's implementation hasn't been done yet due to lack of general support that waifu2x-deratives has been receiving. I haven't tested it myself, but ESRGAN has more setup-overhead than waifu2x-ncnn-vulkan does and what not.

Let me know if there's an SRGAN as easy to use as something like, say waifu2x.
