### ISSUE TITLE
[Feature Request] - Implement other Drivers like realSR

### ISSUE THREAD

**Issue by Felixkruemel** [aka-katto/dandere2x#126]
RealSR is amazing when it comes to upscaling real life footage.

But since it's really slow while upscaling images (way slower than waifu2x-ncnn-vulkan) it would be nice to instead of upscaling video frame by frame use the method you are using for Waifu2x. I would be happy to see that with other drivers as well.

https://github.com/nihui/realsr-ncnn-vulkan

The main concept is the same. It probably should only be necessary to change the command lines for the upscalers. Although I'm not exactly familar with your code.

**Comment by Tremeschin** [comment]
Probably implement srmd-ncnn-vulkan as well?

Implementing both is basically an binary swap on the waifu2x-ncnn-vulkan wrapper command, though realsr has a fixed upscaling ratio = 4 and IIRC no denoise option?

I think that realsr may be a bit undoable for casual upscaling in Dandere2x but that is a personal opinion, it took 1 minute in my GPU to upscale a 480p image whereas Waifu2x a couple seconds, however I never finished an upscale with it so probably will do to check some preliminary results at some point.

Can you give some feedback on srmd-ncnn-vulkan upscaling anime / irl? I personally liked it with denoise on the level 6 range for anime but didn't tested for irl footage :(

I don't spend much time testing settings and my eyes just aren't accurate on these image comparisons lol

**Comment by Felixkruemel** [comment]
IRL with srmd is pretty bad in comparison to realSR but still better than Waifu2x.

realSR is so unbelievable good that I even would pay double the time in comparison to Waifu2x. For me it's around 10x slower than SRMD on my RTX2060Super

before:
![sample](https://user-images.githubusercontent.com/12109804/83798344-65bdb400-a6a4-11ea-9c83-d06ea6ea3743.jpg)

After realSR (look in Fullscreen):
![test](https://user-images.githubusercontent.com/12109804/83798474-99004300-a6a4-11ea-9bb2-44120d7934d5.jpg)

**Comment by aka-katto** [comment]
Implementing realSR is definitely is something I'm investigating within the realm of dandere2x, as d2x is designed / intended to work agnostic to the upscaling algorithm used. Given that realSR behaves the way I think it will, I can see it being a reality. 

Although realSR is definitely very slow and not the most practical upscaling method for most users,  realSR can take advantage of a compression algorithm like dandere2x more than waifu2x would (in theory), as any recycled pixels upscaling is IRL minutes or hours saved.

I'll leave the issue hanging and I'll let you know when I start making progress on it. Thanks for showing there's more interest in realSR than I thought there would be

**Comment by Felixkruemel** [comment]
@aka-katto 
realSR just got an update so that it will work with all languages and so every Windows System. 
Now I'm patiently waiting for the Update for Dandere2x

**Comment by Tremeschin** [comment]
You probably can hijack the settings and run realsr tbh, instead of pointing to the waifu2x-ncnn-vulkan.exe on the settings, point to the realsr binary.

You probably want to disable the denoise_level argument and I'm not sure if there is support on the code for such an option to expect different scale levels rather than x2 as realsr works x4 only.

**Comment by Felixkruemel** [comment]
I did try changing the yaml file but had no luck. Fails to upscale with no log output

**Comment by Felixkruemel** [comment]
Hey @aka-katto @Tremeschin are you already working on implementing this?
A guide just for settings in the yaml to use would also be alright since in theory it should work too.

**Comment by Tremeschin** [comment]
Our works kinda got split between the two Dandere2x "versions" / implementations, I work on mine and aka on his but we research stuff together..

And lately I've been focusing on some side projects for some future stuff so I'd say it's up for aka to add these upscalers :)

I can say for sure that the wrapper would be basically the same as the waifu2x vulkan with the names changed, I'm not feeling like implementing it as both I don't remember much aka's code and his style of coding is very different than mine :(

**Comment by Felixkruemel** [comment]
@Tremeschin I'm only looking for faster upscaling methods than Video2x, so wether I use the one from @aka-katto or yours is irrelevant for me. So if you could implement it in your method that would be also okay.

Just hoping to get a faster emthod than upscaling every single pic :/

**Comment by Tremeschin** [comment]
Ya, my project has support for the Waifu2x Vulkan, Waifu2x CPP, RealSR Vulkan and SRMD Vulkan.

My code isn't as stable as I wanted it to be so if you're gonna use it please upscale the 10 second yn_moving video sample if everything is working. Tbh there can be pathing issues under Windows? haven't tested extensively withunder it :p

I personally never upscaled an video with RealSR entirely so if you perhaps could give it a try...

**Comment by Felixkruemel** [comment]
@Tremeschin I will try that at the weekend then. 
Will probably upscale a short 2min trailer or so.

For movies realSR has no movie model yet, they are working on it and saying that it will give better results and will be faster. SO let's hope then.

**Comment by Felixkruemel** [comment]
@Tremeschin So I tried it yesterday with realSR on a 2min 720p Video. And let's say it that way, 12hours later I've got my result which is actually really good and way faster than with Video2x (I would get 9s/frame there lol). 

So thanks for your work then :)

**Comment by Tremeschin** [comment]
@Felixkruemel oh it worked then, I was totally not expecting this, but wow 12 hours lol

Which bleed value you used with RealSR? Was there any blockiness? Was there any bad blocks / noticeable when moving slowly?

Thanks for stress testing my code, this made my day !!

**Comment by Felixkruemel** [comment]
@Tremeschin I actually used the default settings and need to say there is some blockiness and I probably wouldn't use them again.

You **need to include better samples** in your wiki. That's a must. Literally do 3 pictures with different bleed settings for every Upscaler in like a 5s clip. Just for comparison to see which settings are the best for which needs. 

I also tried SRMD, but there the stock settings are unwatchable, the blockiness is insane.

Not to say, realSR isn't meant for movie upscaling as it has no model for it right now. But it still is way way better than SRMD, but not for me. 12hours is too much lol, although I could roughly reuse 40% of the frames (so V2X would take 20h+ ?!).

I will try some proprietary upscalers next and will see wether they perform better or not (I doubt it to be fair).

**Comment by Tremeschin** [comment]
@Felixkruemel 

At least bleed = 2 for SRMD is recommended on the TLDR on [settings wiki about bleed](https://github.com/Tremeschin/dandere2x-tremx/wiki/Dandere2x-settings#bleed) and on the upscaler combobox tooltip on the GUI.

Perhaps force bleed=2 minimum when switching to SRMD?

As for RealSR I wasn't quite sure how much it bleeds on the upscaling so that's why I asked what bleed you used, probably setting it to 2 or 3 at max will fix this RealSR blockiness at the cost of a ~15% bigger session time on every increment of the bleed...

Yes I agree I have to put some demo pictures of the result based on the upscaler and the bleed value somewhere..

About those 12 hours I'd say it's a pretty good result considering RealSR took quite a while even on an RX 5700 XT GPU on a friend's pc to upscale a single 1080p image and yours input was 720p.

40% block recycling isn't really good tbh, what might have happened is that [this setting](https://github.com/Tremeschin/dandere2x-tremx/wiki/Dandere2x-settings#upscale-full-frame-threshold) set a lot of raw images from the video directly to the upscaler as the residual file size was bigger than the frame itself..

I'd say in these situations where you want to upscale a non-anime video (guessing by this percentage recycled) you'd better upscale all frames alone rather than passing Dandere2x on top of it..

Interestingly enough if you change that `upscale-full-frame-threshold` on advanced tab on the GUI called "Full frame threshold" to zero, it'll act pretty much like V2X where every input frame will be the raw image from the video :p

Interesting result here, thanks for giving this feedback.

**Comment by aka-katto** [comment]
Added in https://github.com/aka-katto/dandere2x/tree/quality-of-life
