### ISSUE TITLE
settings not saved/loaded

### ISSUE THREAD

**Issue by yggdrasil75** [aka-katto/dandere2x#140]
I edited the yaml externally while dandere was closed, opened dandere, the settings were the default. I change a few settings, it doesnt save to the yaml.

**Comment by aka-katto** [comment]
This is expected behaviour, let me explain - 

Dandere2x was never supposed to have a GUI, and was added pretty late into production (I'll make a note of this). The GUI is essentially a YAML editor, and loads the settings, and replaces them during runtime with what the user selects. There's some underlying settings you can modify (i.e `developer settings`), but if you truly wanted to use the yaml, you'd need to have a python environment running.
