### ISSUE TITLE
Selecting Waifu2x Models in GUI

### ISSUE THREAD

**Issue by thescratcho** [aka-katto/dandere2x#64]
Please add the feature to select the conv_models in the gui

**Comment by aka-katto** [comment]
This has been talked about a bit, the problem is each upconverter has a series of different models. For example, there's only conv_model and rgb for vulkan, while caffe has much more.

For the time being, being able to edit it in the JSON *seems* enough. I'm working on adding a more advanced GUI in the future, as the current GUI is really minimal
