### ISSUE TITLE
Why the output video not is MP4

### ISSUE THREAD

**Issue by cfdxkk** [aka-katto/dandere2x#76]
Premiere can not import MKV files.

**Comment by aka-katto** [comment]
I had an issue with one point with 'real time encoding" and mp4 files.

I need to see if the error is still there, ill let you know today or tommorow how it goes

**Comment by aka-katto** [comment]
I looked into it more.. it seems real time encoding didn't work at all with .mkv files.

I can send you a json to use if you want to have .mp4 files, although it may be a bit slower (maybe 5-10 more minutes for a 24 minute video)

**Comment by cfdxkk** [comment]
![TIM图片20190908165651](https://user-images.githubusercontent.com/41364445/64485971-b3160d80-d259-11e9-8915-bc9bebcd0542.jpg)

I used ffmpeg to convert .mkv output video to .mp4, then imported .mp4 video into premiere, but there seems to be some problems.

**Comment by aka-katto** [comment]
> 
> 
> ![TIM图片20190908165651](https://user-images.githubusercontent.com/41364445/64485971-b3160d80-d259-11e9-8915-bc9bebcd0542.jpg)
> 
> I used ffmpeg to convert .mkv output video to .mp4, then imported .mp4 video into premiere, but there seems to be some problems.
> So I hope I can import mp4 directly

Looks like an error with the color profile. Would you be able to upload the video somewhere and I could take a look at it?

**Comment by Tremeschin** [comment]
@cfdxkk Fixed in ffmpeg_pipe_encoding feature I implemented on my branch.

We can't get an mp4 file with traditional means of realtime_encoding (little misleading name on what it does) but it's doable when piping the merged images into ffmpeg.

This feature defaults to an mp4 extension internally when creating the nosound video file so don't forget to set an correct output_file extension

Can you test my default branch (fixes&hacks) for a mp4 file (if it still exists)?

Me and @aka-katto will test all this massive changes before making a big pull request into master branch.

Not closing this issue because it's not fixed here yet :)

**Comment by aka-katto** [comment]
fixed in min_disk
