### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: dandere2x.log

### ISSUE THREAD

**Issue by Trentflix** [aka-katto/dandere2x#83]
I don't have the log open and it shouldn't be used by another process.

recent call last):
  File "gui_driver.py", line 24, in run
  File "wrappers\dandere2x_gui_wrapper.py", line 40, in start
  File "dandere2x.py", line 156, in run_concurrent
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui_driver.py", line 28, in run
  File "wrappers\dandere2x_gui_wrapper.py", line 27, in start
  File "shutil.py", line 513, in rmtree
  File "shutil.py", line 397, in _rmtree_unsafe
  File "shutil.py", line 395, in _rmtree_unsafe
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Home\\Downloads\\1.5.1_release\\workspace\\default\\dandere2x.log'

**Comment by Trentflix** [comment]
Here is the dander2x.log file:

INFO:wrappers.ffmpeg.ffmpeg:Applying filter to video...
INFO:root:Could not upscale first file.. check logs file to see what's wrong
INFO:root:Exiting Dandere2x...

**Comment by aka-katto** [comment]
Hmm, it seems logging is causing a lot of issues.

Have you tried to fully delete folder to see if it fixes anything?

**Comment by Trentflix** [comment]
I did delete the entire Workspace folder and it gives the same error (but doesn't actually create a log file of any kind)

**Comment by aka-katto** [comment]
> I did delete the entire Workspace folder and it gives the same error (but doesn't actually create a log file of any kind)

Are you running as administrator? Someone in the telegram had this same error, but I haven't been able to replicate it. 

I'm really interested in finding the source of the issue, thanks for creating an issue about it.

**Comment by Trentflix** [comment]
Look like the same error.

**Comment by aka-katto** [comment]
> 
> 
> Look like the same error.

I'll draft a release to test a fix sometime tonight, I'll notify you. 

The log file has caused so many issues in the past, I'm conjecturing putting it somewhere will help a lot

**Comment by Trentflix** [comment]
I'll keep an eye out, I appreciate the support.

**Comment by aka-katto** [comment]
> 
> 
> I'll keep an eye out, I appreciate the support.

unrelated, is all text files closed? A common issue on my system is I have logs.txt opened in notepad or something and it causes that issue. I'm not sure if its the source of origin for you.

If not, try specifying a dif workspace also

**Comment by aka-katto** [comment]
> 
> 
> I'll keep an eye out, I appreciate the support.

ran into the issue a lot tonight, I found deleting the 'default' folder entirely, creating a new one seemed to be a quick fix. 

I'm not encouraging you to do this yourself as it's a really janky solution, but fixing this is now on my radar.

**Comment by Trentflix** [comment]
deleting the default folder leads to the same behavior for me. Also tried creating a new default folder prior to running but  still the same result (1.5.2).

**Comment by aka-katto** [comment]
I uploaded a 'driver_only file to this release cycle, hoping to fix this issue

https://github.com/aka-katto/dandere2x/releases/tag/0.1.5.5

Let me know if it does - I'm unable to replicate the bug so I'm somewhat reliant on you testing stuff out in order to fix the problem.

This solution involves implementing a try / except, allowing the program to continue even if deleting the folder failed.

Please let me know!

**Comment by Trentflix** [comment]
still having some issues but getting closer I think. Running it as administrator or not I'm getting the same errors. I think there's a new error message that pops up right before it closes but it closes to quickly for me to grab it.

`D:\Restored\Danderer
output_file = D:\Restored\Output_[vulkan][s2][n3][b20][q85].mp4
input_file = D:\Restored\Output.mp4
block_size = 20
image_quality = 85
waifu2x_type = vulkan
D:\Restored\Danderer\workspace\default\
Deleted Folder
Starting Dandere2x
Successfully created the directory D:\Restored\Danderer\workspace\default\encoded\
Creation of the directory D:\Restored\Danderer\workspace\default\ failed
Successfully created the directory D:\Restored\Danderer\workspace\default\residual_images\
Successfully created the directory D:\Restored\Danderer\workspace\default\inputs\
Successfully created the directory D:\Restored\Danderer\workspace\default\residual_data\
Successfully created the directory D:\Restored\Danderer\workspace\default\compressed_static\
Successfully created the directory D:\Restored\Danderer\workspace\default\residual_upscaled\
Successfully created the directory D:\Restored\Danderer\workspace\default\merged\
Successfully created the directory D:\Restored\Danderer\workspace\default\pframe_data\
Successfully created the directory D:\Restored\Danderer\workspace\default\fade_data\
Successfully created the directory D:\Restored\Danderer\workspace\default\correction_data\
Successfully created the directory D:\Restored\Danderer\workspace\default\compressed_moving\
Successfully created the directory D:\Restored\Danderer\workspace\default\debug\
Successfully created the directory D:\Restored\Danderer\workspace\default\temp_image_folder\
Successfully created the directory D:\Restored\Danderer\workspace\default\logs\
Forcing Resizing to match blocksize..
New width -> 700
New height -> 440
dandere2x could not start.. trying again. If it fails, try running as admin..
D:\Restored\Danderer\workspace\default\
Deleted Folder
Trying to delete workspace via RM tree threw PermissionError - Dandere2x may not work.
Creation of directory failed
Starting Dandere2x
Creation of the directory D:\Restored\Danderer\workspace\default\encoded\ failed
Creation of the directory D:\Restored\Danderer\workspace\default\ failed
Creation of the directory D:\Restored\Danderer\workspace\default\residual_images\ failed
Creation of the directory D:\Restored\Danderer\workspace\default\inputs\ failed
Creation of the directory D:\Restored\Danderer\workspace\default\residual_data\ failed
Successfully created the directory D:\Restored\Danderer\workspace\default\compressed_static\
Creation of the directory D:\Restored\Danderer\workspace\default\residual_upscaled\ failed
Creation of the directory D:\Restored\Danderer\workspace\default\merged\ failed
Creation of the directory D:\Restored\Danderer\workspace\default\pframe_data\ failed
Creation of the directory D:\Restored\Danderer\workspace\default\fade_data\ failed
Successfully created the directory D:\Restored\Danderer\workspace\default\correction_data\
Successfully created the directory D:\Restored\Danderer\workspace\default\compressed_moving\
Creation of the directory D:\Restored\Danderer\workspace\default\debug\ failed
Creation of the directory D:\Restored\Danderer\workspace\default\temp_image_folder\ failed
Creation of the directory D:\Restored\Danderer\workspace\default\logs\ failed`

However, when I try the Waifu2x-Caffe it doesn't close but still gets stuck:

' Time to upscale an uncompressed frame: 7.9
Exception in thread Thread-4:ast 10 Frames: 8.56 sec / frame
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "dandere2xlib\core\merge.py", line 95, in merge_loop
  File "dandere2xlib\core\merge.py", line 167, in make_merge_image
  File "dandere2xlib\core\plugins\pframe.py", line 63, in pframe_image
  File "wrappers\frame\frame.py", line 208, in copy_block
  File "wrappers\frame\frame.py", line 240, in check_if_valid
ValueError: Invalid Dimensions for Dandere2x Image, See Log.'

Log File:

'INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\ does not exist, waiting
INFO:wrappers.ffmpeg.ffmpeg:Applying filter to video...
INFO:root:Starting new compress_frames_thread process
INFO:wrappers.dandere2x_cpp:['D:\\Restored\\Danderer\\externals\\dandere2x_cpp.exe', 'D:\\Restored\\Danderer\\workspace\\default\\', '2881', '20', '8', 'n', '1', '.jpg']
INFO:root:Starting new dandere2xcpp_thread process
INFO:root:Starting new merge_thread process
INFO:dandere2xlib.core.residual:('D:\\Restored\\Danderer\\workspace\\default\\', 1, 2881, 20)
INFO:root:Starting new residual_thread process
INFO:root:Starting new waifu2x_thread process
INFO:root:Starting new status_thread process
INFO:root:Starting new min_disk_thread process
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_1.txt does not exist, waiting
INFO:wrappers.frame.frame:D:\Restored\Danderer\workspace\default\residual_upscaled\output_000001.png dne
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_2.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_3.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_4.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_5.txt does not exist, waiting
INFO:wrappers.frame.frame:D:\Restored\Danderer\workspace\default\inputs\frame21.jpg dne
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_6.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_7.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_8.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\pframe_data\pframe_8.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_9.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_10.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_11.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_12.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_13.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_14.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_15.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_16.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_17.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_18.txt does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_19.txt does not exist, waiting
INFO:wrappers.frame.frame:D:\Restored\Danderer\workspace\default\inputs\frame21.jpg dne
INFO:dandere2xlib.core.merge:Upscaling frame 1
INFO:wrappers.frame.frame:D:\Restored\Danderer\workspace\default\residual_upscaled\output_000002.png dne
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_upscaled\output_000002.png does not exist, waiting
INFO:dandere2xlib.core.merge:Upscaling frame 2
INFO:wrappers.frame.frame:D:\Restored\Danderer\workspace\default\residual_upscaled\output_000003.png dne
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_upscaled\output_000003.png does not exist, waiting
INFO:dandere2xlib.core.merge:Upscaling frame 3
INFO:wrappers.frame.frame:D:\Restored\Danderer\workspace\default\residual_upscaled\output_000004.png dne
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_upscaled\output_000004.png does not exist, waiting
INFO:dandere2xlib.utils.dandere2x_utils:D:\Restored\Danderer\workspace\default\residual_data\residual_20.txt does not exist, waiting
INFO:wrappers.frame.frame:D:\Restored\Danderer\workspace\default\inputs\frame22.jpg dne
INFO:dandere2xlib.core.merge:Upscaling frame 4
INFO:wrappers.frame.frame:D:\Restored\Danderer\workspace\default\residual_upscaled\output_000005.png dne
ERROR:wrappers.frame.frame:Input Dimensions Invalid for Copy Block Function, printing variables. Send Tyler this!
ERROR:wrappers.frame.frame:this_x + block_size - 1 > self.width
ERROR:wrappers.frame.frame:59?>2100
ERROR:wrappers.frame.frame:this_y + block_size - 1 > self.height
ERROR:wrappers.frame.frame:1319?>1308
INFO:wrappers.frame.frame:D:\Restored\Danderer\workspace\default\inputs\frame23.jpg dne'

**Comment by aka-katto** [comment]
Interesting - it seems to get through a few frames. 

What's the input video, btw?

**Comment by NomegaGaming** [comment]
I've been following this thread and seeing as the other person hasn't been responding, after what you told him to do it still isn't working- 

`C:\Users\C******\AppData\Local\Dandere2x
output_file = C:\Users\C*****\Desktop\neos massive mess\hh\New folder\Katekyo Hitman REBORN! NCOP8_[caffe][s3][n3][b20][q85].mp4
input_file = C:\Users\C******\Desktop\neos massive mess\hh\New folder\Katekyo Hitman REBORN! NCOP8.mp4
block_size = 20
image_quality = 85
waifu2x_type = caffe
C:\Users\C*****\AppData\Local\Dandere2x\workspace\default\
Deleted Folder
Starting Dandere2x
Successfully created the directory C:\Users\C*****\AppData\Local\Dandere2x\workspace\default\compressed_moving\
Successfully created the directory C:\Users\C*****\AppData\Local\Dandere2x\workspace\default\residual_images\
Successfully created the directory C:\Users\C*****\AppData\Local\Dandere2x\workspace\default\residual_data\
Successfully created the directory C:\Users\C*****\AppData\Local\Dandere2x\workspace\default\compressed_static\
Successfully created the directory C:\Users\C*****\AppData\Local\Dandere2x\workspace\default\fade_data\
Successfully created the directory C:\Users\C*****\AppData\Local\Dandere2x\workspace\default\residual_upscaled\
Successfully created the directory C:\Users\C*****\AppData\Local\Dandere2x\workspace\default\inputs\
Successfully created the directory C:\Users\C*****\AppData\Local\Dandere2x\workspace\default\merged\
Successfully created the directory C:\Users\C*****\AppData\Local\Dandere2x\workspace\default\debug\
Successfully created the directory C:\Users\C*****\AppData\Local\Dandere2x\workspace\default\encoded\
Successfully created the directory C:\Users\C*****\AppData\Local\Dandere2x\workspace\default\logs\
Creation of the directory C:\Users\Christina\AppData\Local\Dandere2x\workspace\default\ failed
Successfully created the directory C:\Users\C*****\AppData\Local\Dandere2x\workspace\default\correction_data\
Successfully created the directory C:\Users\C*****\AppData\Local\Dandere2x\workspace\default\pframe_data\
Successfully created the directory C:\Users\C*****\AppData\Local\Dandere2x\workspace\default\temp_image_folder\
Forcing Resizing to match blocksize..
New width -> 720
New height -> 480
dandere2x could not start.. trying again. If it fails, try running as admin..
C:\Users\C*****\AppData\Local\Dandere2x\workspace\default\
Deleted Folder
Traceback (most recent call last):
  File "gui_driver.py", line 24, in run
  File "wrappers\dandere2x_gui_wrapper.py", line 40, in start
  File "dandere2x.py", line 101, in run_concurrent
  File "dandere2x.py", line 211, in append_video_resize_filter
AttributeError: 'Context' object has no attribute 'config_json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui_driver.py", line 28, in run
  File "wrappers\dandere2x_gui_wrapper.py", line 27, in start
  File "shutil.py", line 513, in rmtree
  File "shutil.py", line 397, in _rmtree_unsafe
  File "shutil.py", line 395, in _rmtree_unsafe
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\C*****\\AppData\\Local\\Dandere2x\\workspace\\default\\dandere2x.log'
`

I couldn't find a log file for some reason..


https://xanditshare.s-ul.eu/B3tMKYCS here's the file I was trying to upscale to 1440p- I was using the caffe converter but I might try the other ones

**Comment by aka-katto** [comment]
should be fixed in 1.6? let me know if not
