### ISSUE TITLE
[Feature request] Linux support would be really nice

### ISSUE THREAD

**Issue by MarshmelloSUCKS** [aka-katto/dandere2x#84]
Not a bug, just saying that I would love to see this on Linux. I'd port it myself if I knew how to, but I don't so...

**Comment by Tremeschin** [comment]
Dandere2x **do** work on Linux currently. I myself as a contributor develop in it!! Perhaps lack of docs is your issue so our fault kinda.

The current problem is that you kinda have to run it from source, however it isn't that complicated and it works for the moment.

Windows binaries are really practical IKR, buuut Linux users should already know at least a few basic Python pip requirements and compiling a C++ code with it (with proper docs)?

If you can't get it to work just ask me here, the instructions are on [this release](https://github.com/aka-katto/dandere2x/releases/tag/0.1.4.5) just please clone the currently **(temporary)** latest branch **min_disk** instead of that one specified of that release like so: 

`git clone -b min_disk https://github.com/aka-katto/dandere2x/`

Since it's a somewhat stable but not final branch any feedback from you will be important for the development of this project so thanks in advance.

I myself don't use venvs so the lines `python3 -m venv venv` and `source venv/bin/activate` on that guide I simply ignored.

And if you happened to be on a Arch-based distro you can use the packages from the AUR: `waifu2x-ncnn-vulkan-git` (preferred) or `waifu2x-converter-cpp-git` instead of the Snap Vulkan one. 

Will be adding more "findable" resources and docs for Linux, thanks for the feedback on this; this is a great reminder for us on the new users since we can't "un-learn" Dandere2x stuff lol
