### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by aka-katto** [aka-katto/dandere2x#9]
I've been cleaning up Dandere2x lately, and some code review from others would be helfpul.

Helping with improper syntax, poor documentation, etc etc are all appreciated.

**Comment by laundmo** [comment]
i took a look at your code and noticed that you use string concatenation for making strings.

since this already only works on python 3.7, you can use f-strings to make strign stuff easier to read and nicer

concatenation: `self.a + " hey " + self.b`
f-strings: `f"{self.a} hey {self.b}"`
or if you dotn want to use f-strings cause theyre new and fancy, `.format()` can also be used to make strings nicer: `"{0.a} hey {0.b}".format(self)`
