### ISSUE TITLE
Realtime

### ISSUE THREAD

**Issue by Mickevincent** [aka-katto/dandere2x#98]
Do you think dandere2x is fast enough to be able to run in real time to upscale 320x240 to 1920x1080 on a modern gpu? If not with scaling, then only the denoiser?

**Comment by aka-katto** [comment]
It's really dependent on the content and hardware.

Content:

In some cases I can see dandere2x being slower than say something like video2x, but especially with anime there's a lot of visual redundancies which makes dandere2x faster in most cases.

Hardware:

Dandere2x is mostly CPU intensive, while waifu2x is GPU intensive. If you have a poweful enough setup, waifu2x can definitely be ran in real time. However, since dandere2x is dependent on the hardware, it's not certain whether or not it can ever achieve "real-timeness" based off hardware alone
